# Generated by Django 6.0.3 on 2026-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.JSONField(),
        ),
    ]
