# Generated by Django 6.0.3 on 2026-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_address_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.JSONField(null=True),
        ),
    ]
